name: 'Build and Test'
description: 'Build and test description'
runs:
  using: composite
  steps:
  - name: Install eb cli
    shell: bash
    run: |
      sudo add-apt-repository ppa:deadsnakes/ppa
      sudo apt-get install python3.7
      curl -O https://bootstrap.pypa.io/get-pip.py
      python3 get-pip.py --user
      export PATH=~/.local/bin:$PATH
      source ~/.bash_profile
      pip install awsebcli --upgrade --user
  - name: Deploy image to elastic beanstalk
    shell: bash
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    run: |
      eb init --region eu-east-1 --platform "Docker" react
      eb deploy React-env
