name: 'Build and Test'
description: 'Build and test description'
inputs:
  aws_key_id:
    description: "aws_key_id"
    required: true
  aws_secret_access_key:
    description: "aws_secret_access_key"
    required: true
runs:
  using: composite
  steps:
  - name: Install eb cli
    shell: bash
    run: |
      sudo add-apt-repository ppa:deadsnakes/ppa
      sudo apt-get install python3.7
      curl -O https://bootstrap.pypa.io/get-pip.py
      python3 get-pip.py --user
      export PATH=~/.local/bin:$PATH
      source ~/.bash_profile
      pip install awsebcli --upgrade --user
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-region: us-east-1
      aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
  - name: Deploy image to elastic beanstalk
    shell: bash
    run: |
      eb init --region us-east-1 --platform "Docker" react
      eb deploy React-env