name: 'Build and Test'
description: 'Build and test description'
inputs:
  aws_key_id:
    description: "aws_key_id"
    required: true
  aws_secret_access_key:
    description: "aws_secret_access_key"
    required: true
runs:
  using: composite
  steps:
  - name: Install eb cli
    shell: bash
    run: |
      sudo add-apt-repository ppa:deadsnakes/ppa
      sudo apt-get install python3.7
      curl -O https://bootstrap.pypa.io/get-pip.py
      python3 get-pip.py --user
      export PATH=~/.local/bin:$PATH
      source ~/.bash_profile
      pip install awsebcli --upgrade --user
  - name: Deploy image to elastic beanstalk
    shell: bash
    env:
      AWS_ACCESS_KEY_ID: "${{ inputs.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ inputs.AWS_SECRET_ACCESS_KEY }}"
    run: |
      - echo -e '[profile eb-cli]\naws_access_key_id = ' $AWS_ACCESS_KEY_ID ' \naws_secret_access_key = ' $AWS_SECRET_ACCESS_KEY > ~/.aws/config
      eb init --region eu-east-1 --platform "Docker" react
      eb deploy React-env
