name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: yonizabari
          password: dckr_pat_S4hCvyVlzAP-UqGAne34Q6mI68g
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.dev
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          tags: yonizabari/frontend:latest
      -
        name: Run npm run test
        uses: addnab/docker-run-action@v3
        with:
          image: yonizabari/frontend:latest
          options: -e CI=true
          run: npm run test
